from .denormalized_detection import DenormalizedDetection
from .aggregation_detection import DenormalizedAggregationDetection, SingleTableAggregationDetection
from .parent_child import ParentChildDetection