from .denormalized_detection import DenormalizedDetection
from .aggregation_detection import DenormalizedAggregationDetection, SingleTableAggregationDetection, ParentChildAggregationDetection
from .parent_child import ParentChildDetection