[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = "syntherela"
version = "0.2.0"
dependencies = [
    "sdv>=1.9.0,<2",
    "seaborn==0.13.2",
    "xgboost==1.7.6",
    "scikit-learn>1.3.1,<1.5"
]
authors = [
  { name="Martin Jurkovic", email="martin.jurkovic19@gmail.com" },
  { name="Valter Hudovernik", email="valter.hudovernik@gmail.com" },
]
description = "SyntheRela - Synthetic Relational Data Generation Benchmark"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["python", "syntherela", "synthetic data", "relational data", "evaluation", "benchmark"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Healthcare Industry"
    ]

[project.optional-dependencies]
dev=[
	"pre-commit",
]

rdl-utility=[
  "relbench[full,example]@git+https://github.com/snap-stanford/relbench.git@main",
  "torch_geometric==2.6.1",
  "tqdm",
  "lightgbm==4.6.0",
  "featuretools==1.31.0",
]

privacy=[
  "syntheval"
]

[project.urls]
Homepage = "https://github.com/martinjurkovic/syntherela"
Issues = "https://github.com/martinjurkovic/syntherela/issues"

[tool.setuptools.packages.find]
where = ["."]

[tool.yapf]
based_on_style = "pep8"
column_limit = 80
indent_width = 4
blank_line_before_nested_class_or_def = true
split_before_expression_after_opening_paren = true
dedent_closing_brackets = true  # Crucial for isort compatibility

[tool.isort]
profile = "black"
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.ruff]  # https://docs.astral.sh/ruff/rules
src = ["syntherela"]
line-length = 80
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "D",  # pydocstyle
]
ignore = [
    "B905",  # TODO Don't ignore "zip with strict=False"
    "D100",  # TODO Don't ignore "Missing docstring in public module"
    "D101",  # TODO Don't ignore "Missing docstring in public class"
    "D102",  # TODO Don't ignore "Missing docstring in public method"
    "D103",  # TODO Don't ignore "Missing docstring in public function"
    "D104",  # TODO Don't ignore "Missing docstring in public package"
    "D105",  # Ignore "Missing docstring in magic method"
    "D107",  # Ignore "Missing docstring in __init__"
    "D205",  # Ignore "blank line required between summary line and description"
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.pydocstyle]
convention = "google"
